[package]
name = "rust_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.3"
image = {version = "0.25.8", features = ["jpeg", "png", "gif", "webp", "bmp", "tiff", "ico", "qoi"]}
clap = { version = "*", features = ["derive"] }
rustc-hash = "*"
colored = "3.0.0"
regex = "1.12.2"
base64 = "0.22.1"

